version: '3'
services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - hotel_network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: hotel_webserver
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - hotel_network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: hotel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hotel_booking
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: hotel_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    volumes:
      - hotel_dbdata:/var/lib/mysql
    networks:
      - hotel_network

  # phpMyAdmin Service (optional but helpful)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hotel_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8081:80'
    networks:
      - hotel_network
    depends_on:
      - db

networks:
  hotel_network:
    driver: bridge

volumes:
  hotel_dbdata:
